POST http://localhost:8888/Orizon/api/paese/create.php
Content-Type: application/json

{
    "nome": "Italia"
}

### (Fallo due volte per avere ID 1 e ID 2)
POST http://localhost:8888/Orizon/api/paese/create.php
Content-Type: application/json

{
    "nome": "Francia"
}

### 3. Crea Viaggio
POST http://localhost:8888/Orizon/api/viaggio/create.php
Content-Type: application/json

{
    "posti_disponibili": 15,
    "paesi_ids": [5, 6] 
}

### 3. Vedi tutti i viaggi
GET http://localhost:8888/Orizon/api/viaggio/read.php

### 3. Filtra per paese
http://localhost:8888/Orizon/api/viaggio/read.php?paese_id=5

### 4. Filtra per i posti
http://localhost:8888/Orizon/api/viaggio/read.php?posti=20

### 5. Eliminare un viaggio
DELETE http://localhost:8888/Orizon/api/viaggio/delete.php
Content-Type: application/json

{
    "id": 26
}

### 6. Aggiornamento dati
PUT http://localhost:8888/Orizon/api/viaggio/update.php
Content-Type: application/json

{
    "id": 25,
    "posti_disponibili": 50,
    "paesi_ids": [5, 6]
}